name: Build and Release

on:
    push:
        branches: [master]

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m "Release ${{ github.ref }}" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
