name: Lint and Test

on:
    pull_request:
        branches: [master]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.36

            - name: Install dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test

            - name: Check if dist is up to date
              run: |
                  yarn build
                  if [ "$(git diff --name-only dist)" ]; then
                      echo "::error::The dist file is not up to date. Please run 'yarn build' and commit the changes before pushing."
                      exit 1
                  fi
