name: Tag Release

on:
    push:
        branches: [master]

jobs:
    tag-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v1

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  latest_tag=$(git tag --sort=-version:refname --list 'v*[0-9].*[0-9].*[0-9]' | head -n 1)
                  latest_tag=${latest_tag#v}  # Remove the 'v' prefix if present
                  echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

            - name: Bump patch version
              id: bump_patch_version
              run: |
                  IFS='.' read -r major minor patch <<< "${{ steps.get_latest_tag.outputs.latest_tag }}"
                  new_tag="${major}.${minor}.$((patch + 1))"
                  echo "new_tag=${new_tag}" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.bump_patch_version.outputs.new_tag }}
                  release_name: Release ${{ steps.bump_patch_version.outputs.new_tag }}
                  draft: false
                  prerelease: false
